<?php

namespace ME\EmCore\Http\Controllers;

use Illuminate\Http\Request;
use ME\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class BirthdayController extends Controller
{
    public function wish($name)
    {

        // URL থেকে আসা name decode করুন
        $name = urldecode($name);
        // 100 টা professional & fun birthday wishes (উদাহরণ)
        $wishes = [
            'en' => [
                "Happy Birthday, $name! Wishing you a year full of success and joy!",
                "Cheers to your special day, $name! May all your dreams come true.",
                "Happy Birthday, $name! Keep shining like the star you are.",
                "Wishing you a fabulous birthday, $name! Stay awesome and blessed.",
                "Another year wiser! Happy Birthday, $name!",
                "Sending you smiles for every moment of your special day, $name!",
                "Hope your birthday is as wonderful as you are, $name!",
                "Enjoy your special day to the fullest, $name!",
                "May your birthday be filled with love, $name!",
                "Happy Birthday, $name! Celebrate and enjoy!",
                "Wishing you endless happiness today and always, $name!",
                "Happy Birthday, $name! Stay blessed and happy.",
                "Cheers to another beautiful year of life, $name!",
                "Happy Birthday, $name! May your heart be filled with joy.",
                "Wishing you a day that sparkles with happiness, $name!",
                "May this birthday bring you countless blessings, $name!",
                "Happy Birthday, $name! Keep smiling brightly.",
                "Wishing you love, laughter, and endless joy, $name!",
                "Happy Birthday, $name! You deserve all the happiness.",
                "May your dreams take flight this year, $name!",
                "Happy Birthday, $name! Make a wish and enjoy your day.",
                "Hope your day is filled with sweet surprises, $name!",
                "Happy Birthday, $name! Keep being amazing.",
                "Wishing you a magical birthday full of wonderful moments, $name!",
                "Happy Birthday, $name! May your year shine brighter than ever.",
                "Sending birthday hugs and love your way, $name!",
                "Happy Birthday, $name! May your smile never fade.",
                "Hope your birthday is as awesome as you are, $name!",
                "Wishing you a birthday full of love and laughter, $name!",
                "Cheers to you, $name! Have an unforgettable birthday.",
                "Happy Birthday, $name! May your life be filled with blessings.",
                "Wishing you joy in every moment today, $name!",
                "May this new year bring new opportunities, $name!",
                "Happy Birthday, $name! Celebrate like there’s no tomorrow.",
                "Sending warm wishes on your birthday, $name!",
                "Happy Birthday, $name! You are truly special.",
                "May your birthday be filled with sunshine and smiles, $name!",
                "Wishing you everything beautiful on your special day, $name!",
                "Happy Birthday, $name! Enjoy every second of your day.",
                "Wishing you a year filled with prosperity, $name!",
                "Happy Birthday, $name! Keep chasing your dreams.",
                "May this birthday mark the beginning of something amazing, $name!",
                "Wishing you health, wealth, and happiness, $name!",
                "Happy Birthday, $name! Keep spreading positivity.",
                "Enjoy your special day surrounded by love, $name!",
                "Wishing you endless blessings today, $name!",
                "Happy Birthday, $name! Stay happy and blessed.",
                "May your heart be filled with joy today, $name!",
                "Happy Birthday, $name! You deserve the world.",
                "Wishing you all the success in the world, $name!",
                "Happy Birthday, $name! Stay bold and beautiful.",
                "Hope all your wishes come true today, $name!",
                "Wishing you laughter and cheer all year long, $name!",
                "Happy Birthday, $name! Enjoy every beautiful moment.",
                "May this birthday open new doors for you, $name!",
                "Happy Birthday, $name! Stay amazing just the way you are.",
                "Wishing you a birthday as bright as your smile, $name!",
                "Happy Birthday, $name! Celebrate with joy.",
                "May God bless you with happiness and success, $name!",
                "Wishing you a wonderful birthday celebration, $name!",
                "Happy Birthday, $name! You make the world brighter.",
                "Sending you positive vibes on your birthday, $name!",
                "Wishing you love and happiness today, $name!",
                "Happy Birthday, $name! Make unforgettable memories today.",
                "May this year be the best one yet, $name!",
                "Happy Birthday, $name! Keep shining beautifully.",
                "Wishing you joy, peace, and prosperity, $name!",
                "Happy Birthday, $name! Always stay blessed.",
                "Wishing you a colorful and joyful birthday, $name!",
                "Happy Birthday, $name! Celebrate your uniqueness.",
                "May your special day be full of excitement, $name!",
                "Wishing you blessings in abundance, $name!",
                "Happy Birthday, $name! Keep smiling always.",
                "Hope your day is filled with joy and wonder, $name!",
                "Happy Birthday, $name! You are truly cherished.",
                "May this birthday bring you closer to your dreams, $name!",
                "Wishing you a sweet and memorable birthday, $name!",
                "Happy Birthday, $name! Keep shining your light.",
                "Wishing you a year full of love and laughter, $name!",
                "Happy Birthday, $name! Stay bold, stay kind.",
                "May your birthday be as amazing as you, $name!",
                "Wishing you happiness that lasts forever, $name!",
                "Happy Birthday, $name! Keep being wonderful.",
                "Hope your birthday is filled with blessings, $name!",
                "Wishing you all the joy you can hold, $name!",
                "Happy Birthday, $name! Keep dreaming big.",
                "May your birthday fill your heart with warmth, $name!",
                "Wishing you endless reasons to smile, $name!",
                "Happy Birthday, $name! You're a gift to the world.",
                "May your life be filled with love and light, $name!",
                "Wishing you a joyful and unforgettable birthday, $name!",
                "Happy Birthday, $name! Celebrate the amazing person you are.",
                "May this day bring peace to your heart, $name!",
                "Wishing you success in everything you pursue, $name!",
                "Happy Birthday, $name! Enjoy this beautiful journey of life."
            ],

            'bn' => [
                "শুভ জন্মদিন, $name! সফলতা ও আনন্দে ভরা একটি বছর কাটুক তোমার!",
                "তোমার বিশেষ দিনে শুভেচ্ছা, $name! তোমার সব স্বপ্ন পূরণ হোক।",
                "শুভ জন্মদিন, $name! তুমি তারার মতোই জ্বলতে থাকো।",
                "দারুণ একটি জন্মদিনের শুভেচ্ছা, $name! সুখী ও আশীর্বাদপুষ্ট থাকো।",
                "আরো একটি বছর বুদ্ধিমত্তার! শুভ জন্মদিন, $name!",
                "তোমার বিশেষ দিনের প্রতিটি মুহূর্ত হাসিতে ভরে উঠুক, $name!",
                "তোমার জন্মদিন তোমার মতোই সুন্দর হোক, $name!",
                "তোমার বিশেষ দিনটি পুরোপুরি উপভোগ করো, $name!",
                "তোমার জন্মদিন ভালোবাসায় ভরে উঠুক, $name!",
                "শুভ জন্মদিন, $name! উদযাপন করো আর আনন্দে থাকো!",
                "আজ ও সর্বদা তোমার জন্য অশেষ সুখের কামনা, $name!",
                "শুভ জন্মদিন, $name! সুখী ও আশীর্বাদপুষ্ট থাকো।",
                "জীবনের আরেকটি সুন্দর বছরের জন্য অভিনন্দন, $name!",
                "শুভ জন্মদিন, $name! তোমার হৃদয় আনন্দে ভরে উঠুক।",
                "তোমার দিনটি সুখে ঝলমল করুক, $name!",
                "এই জন্মদিন তোমার জন্য অসংখ্য আশীর্বাদ নিয়ে আসুক, $name!",
                "শুভ জন্মদিন, $name! তোমার হাসি কখনো যেন ম্লান না হয়।",
                "ভালোবাসা, হাসি আর আনন্দে ভরে উঠুক তোমার দিন, $name!",
                "শুভ জন্মদিন, $name! তুমি সব সুখ পাওয়ার যোগ্য।",
                "এই বছর তোমার স্বপ্নগুলো পূর্ণ হোক, $name!",
                "শুভ জন্মদিন, $name! ইচ্ছা করো আর উদযাপন করো।",
                "তোমার দিনটি মিষ্টি চমকে ভরে উঠুক, $name!",
                "শুভ জন্মদিন, $name! অসাধারণ থেকো।",
                "তোমার জন্মদিনটি হোক জাদুকরী মুহূর্তে ভরা, $name!",
                "শুভ জন্মদিন, $name! তোমার বছরটি ঝলমলে কাটুক।",
                "জন্মদিনে তোমার জন্য ভালোবাসা ও আলিঙ্গন, $name!",
                "শুভ জন্মদিন, $name! তোমার হাসি সারাজীবন টিকে থাকুক।",
                "তোমার জন্মদিন তোমার মতোই অসাধারণ হোক, $name!",
                "হাসি ও ভালোবাসায় ভরা হোক তোমার জন্মদিন, $name!",
                "তোমার জন্য বিশেষ শুভেচ্ছা রইলো, $name!",
                "শুভ জন্মদিন, $name! তোমার জীবন আশীর্বাদে ভরে উঠুক।",
                "আজকের প্রতিটি মুহূর্ত আনন্দে ভরে উঠুক, $name!",
                "নতুন বছরটি নতুন সুযোগ নিয়ে আসুক, $name!",
                "শুভ জন্মদিন, $name! আজ তুমি সবচেয়ে বিশেষ।",
                "তোমার জন্মদিন উষ্ণ শুভেচ্ছায় ভরে উঠুক, $name!",
                "শুভ জন্মদিন, $name! তুমি সত্যিই বিশেষ।",
                "তোমার জন্মদিন হোক রোদ ও হাসিতে ভরা, $name!",
                "তোমার বিশেষ দিনটি হোক রঙিন ও সুন্দর, $name!",
                "শুভ জন্মদিন, $name! তোমার দিনটি উপভোগ করো।",
                "পুরো বছরটি সমৃদ্ধিতে ভরে উঠুক, $name!",
                "শুভ জন্মদিন, $name! তোমার স্বপ্নের পথে এগিয়ে যাও।",
                "এই জন্মদিন তোমার জীবনে নতুন কিছু শুরু করুক, $name!",
                "স্বাস্থ্য, সুখ ও সমৃদ্ধি থাকুক তোমার জীবনে, $name!",
                "শুভ জন্মদিন, $name! ইতিবাচকতা ছড়িয়ে যাও।",
                "ভালোবাসায় ঘেরা থাকুক তোমার দিন, $name!",
                "আজকের দিনটি তোমার জন্য আশীর্বাদ বয়ে আনুক, $name!",
                "শুভ জন্মদিন, $name! সবসময় সুখে থাকো।",
                "তোমার হৃদয় আজ আনন্দে ভরে উঠুক, $name!",
                "শুভ জন্মদিন, $name! তুমি পৃথিবীর সেরা প্রাপ্য।",
                "তোমার সফলতার জন্য রইলো শুভকামনা, $name!",
                "শুভ জন্মদিন, $name! তুমি সাহসী ও সুন্দর থাকো।",
                "তোমার সব ইচ্ছা পূরণ হোক, $name!",
                "পুরো বছরটি হাসি-আনন্দে কেটে যাক, $name!",
                "শুভ জন্মদিন, $name! প্রতিটি মুহূর্ত উপভোগ করো।",
                "এই জন্মদিন তোমার জীবনে নতুন দরজা খুলুক, $name!",
                "শুভ জন্মদিন, $name! তুমি যেরকম, ঠিক সেরকমই থেকো।",
                "তোমার হাসির মতোই উজ্জ্বল হোক তোমার দিন, $name!",
                "শুভ জন্মদিন, $name! আনন্দে ভরে উঠুক দিনটি।",
                "আল্লাহ তোমাকে সুখ ও সাফল্য দান করুন, $name!",
                "তোমার জন্মদিনের অনুষ্ঠানটি দারুণ হোক, $name!",
                "শুভ জন্মদিন, $name! তোমার উপস্থিতি পৃথিবীকে সুন্দর করে।",
                "তোমার জন্মদিনে রইলো ইতিবাচক শক্তি, $name!",
                "ভালোবাসা ও আনন্দে ভরে উঠুক তোমার জন্মদিন, $name!",
                "শুভ জন্মদিন, $name! অবিস্মরণীয় মুহূর্ত তৈরি করো।",
                "এই বছরটি তোমার জীবনের সেরা হয়ে উঠুক, $name!",
                "শুভ জন্মদিন, $name! তুমি সত্যিই উজ্জ্বল একটি মানুষ।",
                "তোমার জীবনে শান্তি, আনন্দ ও সমৃদ্ধি আসুক, $name!",
                "শুভ জন্মদিন, $name! সবসময় আশীর্বাদপুষ্ট থাকো।",
                "রঙিন ও আনন্দময় হোক তোমার জন্মদিন, $name!",
                "শুভ জন্মদিন, $name! তোমার স্বকীয়তাকে উদযাপন করো।",
                "উত্তেজনা ও আনন্দে ভরে উঠুক তোমার দিন, $name!",
                "তোমার জীবনে অশেষ আশীর্বাদ বর্ষিত হোক, $name!",
                "শুভ জন্মদিন, $name! সবসময় হাসিখুশি থাকো।",
                "তোমার দিনটি আনন্দে ভরে উঠুক, $name!",
                "শুভ জন্মদিন, $name! তুমি সত্যিই মূল্যবান।",
                "স্বপ্নপূরণের পথে আরো এগিয়ে যাও, $name!",
                "তোমার জন্মদিনটি অতুলনীয় হোক, $name!",
                "শুভ জন্মদিন, $name! তোমার আলো ছড়িয়ে দাও।",
                "ভালোবাসা ও হাসিতে ভরা একটি বছর কাটুক, $name!",
                "শুভ জন্মদিন, $name! দয়ালু ও সাহসী থেকো।",
                "তোমার জন্মদিন তোমার মতোই অসাধারণ হোক, $name!",
                "অবিরাম সুখে ভরে উঠুক তোমার জীবন, $name!",
                "শুভ জন্মদিন, $name! তুমি দারুণ এক মানব।",
                "তোমার জন্মদিন আশীর্বাদে ভরা হোক, $name!",
                "অশেষ আনন্দ পাও তুমি, $name!",
                "শুভ জন্মদিন, $name! বড় স্বপ্ন দেখো।",
                "তোমার হৃদয় উষ্ণতায় ভরে উঠুক আজ, $name!",
                "অন্তহীন হাসির কারণ খুঁজে পাও, $name!",
                "শুভ জন্মদিন, $name! তুমি পৃথিবীর জন্য একটি উপহার।",
                "তোমার জীবন ভালোবাসা ও আলোর পথে এগোক, $name!",
                "তোমার জন্মদিনটি হোক আনন্দময় ও স্মরণীয়, $name!",
                "শুভ জন্মদিন, $name! তুমি এক অসাধারণ মানুষ।",
                "আজকের দিনটি তোমার হৃদয়ে শান্তি আনুক, $name!",
                "তোমার প্রতিটি প্রচেষ্টায় সাফল্য আসুক, $name!",
                "শুভ জন্মদিন, $name! জীবনের সুন্দর যাত্রা উপভোগ করো।"
            ]
        ];


        // random wish
        // $randomWish = $wishes[array_rand($wishes)];
        $language = Session::get('locale') ?? 'en';

        $randomWish = $wishes[$language][array_rand($wishes[$language])];


        return view('em_core::birthday.wish', compact('name', 'randomWish'));
    }
}
